<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Isbak_SAR_Guide.DataAccess\Isbak_SAR_Guide.DataAccess.csproj" />
    <ProjectReference Include="..\Isbak_SAR_Guide.Entities\Isbak_SAR_Guide.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Mapster" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.11" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

</Project>
